server:
  port: 8082

spring:
  application:
    name: ORDER-SERVICE
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5435/paymentdb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  config:
    import: configserver:http://localhost:9296
